#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"


if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/DomePlugIns/"

cp "/tmp/LunaticoBeaver_X2/domelist LunaticoBeaver.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/DomePlugIns/LunaticoBeaver.ui"
cp "/tmp/LunaticoBeaver_X2/LunaticoBeaver.ui" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/DomePlugIns/LunaticoBeaver.png"
cp "/tmp/LunaticoBeaver_X2/Lunatico.png" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/DomePlugIns/libLunaticoBeaver.dylib"
cp "/tmp/LunaticoBeaver_X2/libLunaticoBeaver.dylib" "$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist LunaticoBeaver.txt"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/LunaticoBeaver.ui"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/Lunatico.png"
	chown $app_owner "$PLUGINS_DIR/DomePlugIns/libLunaticoBeaver.dylib"
fi

rm -rf /tmp/LunaticoBeaver_X2
